(setf aveiro (make-cidade 'aveiro nil nil nil))
(setf viseu (make-cidade 'viseu nil nil nil))
(setf braga (make-cidade 'braga nil nil nil))
(setf v-castelo (make-cidade 'v-castelo nil nil nil))
(setf braganca (make-cidade 'braganca nil nil nil))
(setf beja (make-cidade 'beja nil nil nil))
(setf setubal (make-cidade 'setubal nil nil nil))
(setf c-branco (make-cidade 'c-branco nil nil nil))
(setf coimbra (make-cidade 'coimbra nil nil nil))
(setf evora (make-cidade 'evora nil nil nil))
(setf portalegre (make-cidade 'portalegre nil nil nil))
(setf faro (make-cidade 'faro nil nil nil))
(setf guarda (make-cidade 'guarda nil nil nil))
(setf leiria (make-cidade 'leiria nil nil nil))
(setf santarem (make-cidade 'santarem nil nil nil))
(setf lisboa (make-cidade 'lisboa nil nil nil))
(setf setubal (make-cidade 'setubal nil nil nil))
(setf porto (make-cidade 'porto nil nil nil))
(setf v-real (make-cidade 'v-real nil nil nil))
(setf viana (make-cidade 'viana nil nil nil))

(setf grafo 
	(list 
		(list aveiro (make-cidade 'porto aveiro 68 0) (make-cidade 'viseu aveiro 95 0) (make-cidade 'coimbra aveiro 68 0) (make-cidade 'leiria aveiro 115 0))
		(list viseu (make-cidade 'aveiro viseu 95 0) (make-cidade 'porto viseu 133 0) (make-cidade 'v-real viseu 110 0) (make-cidade 'guarda viseu 85 0) (make-cidade 'coimbra viseu 96 0))
		(list braga (make-cidade 'viana braga 48 0) (make-cidade 'v-real braga 106 0) (make-cidade 'porto braga 53 0))
		(list v-castelo (make-cidade 'braga v-castelo 48 0) (make-cidade 'porto v-castelo 71 0) )
		(list braganca (make-cidade 'v-real braganca 137 0) (make-cidade 'guarda braganca 202 0))
		(list beja (make-cidade 'evora beja 78 0) (make-cidade 'faro beja 152 0)(make-cidade 'setubal beja 142 0))
		(list setubal (make-cidade 'lisboa setubal 50 0) (make-cidade 'evora setubal 103 0)(make-cidade 'beja setubal 142 0) (make-cidade 'faro setubal 249 0))
		(list c-branco (make-cidade 'coimbra c-branco 159 0) (make-cidade 'guarda c-branco 106 0)(make-cidade 'portalegre c-branco 80 0)(make-cidade 'evora c-branco 203 0))
		(list coimbra (make-cidade 'viseu coimbra 96 0) (make-cidade 'leiria coimbra 67 0))
		(list evora (make-cidade 'lisboa evora 150 0) (make-cidade 'santarem evora 117 0) (make-cidade 'portalegre evora 131 0) (make-cidade 'setubal evora 103 0) (make-cidade 'beja evora 78 0))
		(list portalegre (make-cidade 'evora portalegre 131 0) (make-cidade 'c-branco portalegre 80 0))
		(list faro (make-cidade 'setubal faro 249 0) (make-cidade 'lisboa faro 299 0))
		(list guarda (make-cidade 'v-real guarda 157 0) (make-cidade 'viseu guarda 85 0))
		(list leiria (make-cidade 'lisboa leiria 129 0) (make-cidade 'santarem leiria 70 0))
		(list santarem (make-cidade 'leiria santarem 70 0) (make-cidade 'lisboa santarem 78 0) (make-cidade 'evora santarem 117 0))
		(list lisboa (make-cidade 'santarem lisboa 78 0) (make-cidade 'setubal lisboa 50 0))
		(list setubal (make-cidade 'lisboa setubal 50 0) (make-cidade 'beja setubal 142 0) (make-cidade 'faro setubal 249 0))
		(list porto (make-cidade 'v-castelo porto 71 0) (make-cidade 'v-real porto 116 0) (make-cidade 'viseu porto 133 0))
		(list v-real (make-cidade 'viseu v-real 110 0))
		(list viana (make-cidade 'braga viana 48 0))
	)
)

(setf heuristica-faro
	(list
		(list v-real 429)
		(list aveiro 366)
		(list viseu 363)
		(list braga 454)
		(list v-castelo 473)
		(list braganca 487)
		(list beja 99)
		(list setubal 168)
		(list c-branco 280)
		(list coimbra 319)
		(list evora 157)
		(list portalegre 228)
		(list faro 0)
		(list guarda 352)
		(list leiria 278)
		(list santarem 231)
		(list lisboa 195)
		(list setubal 168)
		(list porto 418)
		(list viana 494)
	)
)